export enum Keyword {
  CAT = 'cat',
  DOG = 'dog',
  PERSON = 'person',
  CAR = 'car',
  GLACIER = 'glacier',
  FOREST = 'forest',
  SEA = 'sea',
  BUILDINGS = 'buildings',
  STREET = 'street',
  MOUNTAIN = 'mountain',
  DINING_TABLE = 'dining table',
  KITE = 'kite',
  BEAR = 'bear',
  HORSE = 'horse',
  ELEPHANT = 'elephant',
  BIRD = 'bird',
  BOAT = 'boat',
  surfboard = 'surfboard',
  spoon = 'spoon',
  baseball_bat = 'baseball bat',
  knife = 'knife',
  mouse = 'mouse',
  cow = 'cow',
  bed = 'bed',
  apple = 'apple',
}

export enum Genres {
  ACTION = 'Action',
  ADVENTURE = 'Adventure',
  ANIMATION = 'Animation',
  COMEDY = 'Comedy',
  DRAMA = 'Drama',
  DOCUMENTARY = 'Documentary',
  FAMILY = 'Family',
  FANTASY = 'Fantasy',
  FOREIGN = 'Foreign',
  ROMANCE = 'Romance',
  SCIENCE_FICTION = 'Science Fiction',
  THRILLER = 'Thriller',
  TV_MOVIE = 'TV Movie',
}
